<?php

use Illuminate\Database\Seeder;

class MenuTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $table = \Illuminate\Support\Facades\DB::table('menus');
        $data = [
            [
                'id'=>1,
                'parent_id'=>0,
                'name'=>'主页',
                'path'=>'/home',
                'component'=>'Home',
                'icon'=>null,
                'meta'=>json_encode(['title'=>'首页']),
            ],
            [
                'id'=>2,
                'parent_id'=>0,
                'name'=>'后台用户管理',
                'path'=>null,
                'component'=>null,
                'icon'=>null,
                'meta'=>json_encode(['title'=>'后台用户管理']),
            ],
            [
                'id'=>3,
                'parent_id'=>0,
                'name'=>'角色管理',
                'path'=>null,
                'component'=>null,
                'icon'=>null,
                'meta'=>json_encode(['title'=>'角色管理']),
            ],
            [
                'id'=>4,
                'parent_id'=>0,
                'name'=>'手机用户管理',
                'path'=>null,
                'component'=>null,
                'icon'=>null,
                'meta'=>json_encode(['title'=>'角色管理']),
            ],
            [
                'id'=>5,
                'parent_id'=>2,
                'name'=>'后台用户列表',
                'path'=>'/admin',
                'component'=>'Admin',
                'icon'=>null,
                'meta'=>json_encode(['title'=>'账号列表']),
            ],
            [
                'id'=>6,
                'parent_id'=>3,
                'name'=>'角色列表',
                'path'=>'/role',
                'component'=>'Role',
                'icon'=>null,
                'meta'=>json_encode(['title'=>'角色列表']),
            ],
            [
                'id'=>7,
                'parent_id'=>4,
                'name'=>'手机用户列表',
                'path'=>'/user',
                'component'=>'User',
                'icon'=>null,
                'meta'=>json_encode(['title'=>'角色列表']),
            ],
            [
                'id'=>8,
                'parent_id'=>0,
                'name'=>'产品科目管理',
                'path'=>null,
                'component'=>null,
                'icon'=>null,
                'meta'=>json_encode(['title'=>'产品科目管理']),
            ],
            [
                'id'=>9,
                'parent_id'=>0,
                'name'=>'科目分类管理',
                'path'=>null,
                'component'=>null,
                'icon'=>null,
                'meta'=>json_encode(['title'=>'科目分类管理']),
            ],
            [
                'id'=>10,
                'parent_id'=>8,
                'name'=>'产品科目列表',
                'path'=>'/product',
                'component'=>'Product',
                'icon'=>null,
                'meta'=>json_encode(['title'=>'产品科目列表']),
            ],
            [
                'id'=>11,
                'parent_id'=>9,
                'name'=>'科目分类列表',
                'path'=>'/category',
                'component'=>'Category',
                'icon'=>null,
                'meta'=>json_encode(['title'=>'科目分类列表']),
            ],
            [
                'id'=>12,
                'parent_id'=>0,
                'name'=>'数据统计',
                'path'=>null,
                'component'=>null,
                'icon'=>null,
                'meta'=>json_encode(['title'=>'数据统计']),
            ],
            [
                'id'=>13,
                'parent_id'=>12,
                'name'=>'今日统计',
                'path'=>'/statistics-today',
                'component'=>'StatisticsToday',
                'icon'=>null,
                'meta'=>json_encode(['title'=>'今日统计']),
            ],
        ];
        $table->truncate();
        $table->insert($data);
    }
}
